export const LOGIN_OUT = 'LOGIN_OUT';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_USERNAME_ADD = 'LOGIN_USERNAME_ADD';
export const LOGIN_PASSWORD_ADD = 'LOGIN_PASSWORD_ADD';
export const LOGIN_DATA_ADD = 'LOGIN_DATA_ADD';
